services:
  app:
    build: .
    restart: always
    env_file:
      - variablea.env
    depends_on:
      - database
      - cache
      - server
    links:
      - database
      - cache
      - server
    volumes:
      - .:/app
  database:
    image: mysql
    restart: always
    expose:
      -  "3360"
    ports:
      - "3360:3360"
  cache:
    image: redis
    restart: always
    ports:
      - "3000:8000"
    expose:
      - "8000"
  server:
    image: httpd
    expose:
      - "5000"
    ports:
      - "9000:5000"
    
